# -*- coding: utf-8 -*-
"""daily chalenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DwqdA4x_NyIGlkACpONsx24nTQwCMSrL

Instructions
Using the input function, ask the user for a string. The string must be 10 characters long.
If it’s less than 10 characters, print a message which states “string not long enough”.
If it’s more than 10 characters, print a message which states “string too long”.
If it’s 10 characters, print a message which states “perfect string” and continue the exercise.

Then, print the first and last characters of the given text.
The user enters "HelloWorld"
Then you have to print
H
d


3. Using a for loop, construct the string character by character: Print the first character, then the second, then the third, until the full string is printed. For example:

The user enters "HelloWorld"
Then, you have to construct the string character by character
H
He
Hel
... etc
HelloWorld


4. Bonus: Swap some characters around then print the newly jumbled string (hint: look into the shuffle method). For example:

Hlrolelwod
"""

user_string=str(input("Please enter a string that is 10 characters long: "))
if len(user_string) < 10:
  print("String not long enough")
elif len(user_string) > 10:
  print("String too long")
else:
  print("Perfect string")
  print(user_string[0])
  print(user_string[-1])
  current_string = ""
  for i in range(len(user_string)):
    current_string += user_string[i]
    print(current_string)
  shuffled_string = list(user_string)
  import random
  random.shuffle(shuffled_string)
  print("".join(shuffled_string))