# -*- coding: utf-8 -*-
"""excersise xp gold

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1570A4lfOkMXIXIdjQaDTlgNVy0JOfVCF

Exercise 1 : Hello World-I love Python
Instructions
Print the following output in one line of code:

Hello world
Hello world
Hello world
Hello world
I love python
I love python
I love python
I love python
"""

print(("hello world"*4)+("i love python"*4))

"""Exercise 2 : What is the Season ?
Instructions
Ask the user to input a month (1 to 12).
Display the season of the month received :
Spring runs from March (3) to May (5)
Summer runs from June (6) to August (8)
Autumn runs from September (9) to November (11)
Winter runs from December (12) to February (2)

"""

user_month = int(input("please enter a month (1 to 12): "))

if user_month in [3, 4, 5]:
  print("Spring")
elif user_month in [6, 7, 8]:
  print("Summer")
elif user_month in [9, 10, 11]:
  print("Autumn")
elif user_month in [12, 1, 2]:
  print("Winter")