# -*- coding: utf-8 -*-
"""excersise xp ninja

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZ6ffOnE4FW1RDJhaiZNXGwdE3m1Coka

Exercise 1 : Use the terminal
Instructions
Run this command in the terminal to open a python console:
$ python3
Hint: Replace python3 with python for Windows

Read about the PATH variable. Try to explain why you can call python3 if you aren’t in the executable directory.
PATH explanation can be found here.
"""

!python3

"""Exercise 2 : Alias
Instructions
Read about alias, and try to open a python console with the command:

$ py

"""

!python

"""Exercise 3 : Outputs
Instructions
Predict the output of the following code snippets:

    >>> 3 <= 3 < 9
    >>> 3 == 3 == 3
    >>> bool(0)
    >>> bool(5 == "5")
    >>> bool(4 == 4) == bool("4" == "4")
    >>> bool(bool(None))
    x = (1 == True)
    y = (1 == False)
    a = True + 4
    b = False + 10

    print("x is", x)
    print("y is", y)
    print("a:", a)
    print("b:
"""

3<=3<9 # true
3==3==3 # true
bool(0) # false
bool(5=="5") # false
bool(4==4)==bool("4"=="4") # true
bool(bool(None)) # false
x = (1 == True)
y = (1 == False)
a = True + 4
b = False + 10

print("x is", x)
print("y is", y)
print("a:", a)
print("b:", b)

"""Exercise 4 : How many characters in a sentence ?
Instructions
Use python to find out how many characters are in the following text, use a single line of code (beyond the establishment of your my_text variable).

my_text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit,
           sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
           Ut enim ad minim veniam, quis nostrud exercitation ullamco
           laboris nisi ut aliquip ex ea commodo consequat.
           Duis aute irure dolor in reprehenderit in voluptate velit
           esse cillum dolore eu fugiat nulla pariatur.
           Excepteur sint occaecat cupidatat non proident,
           sunt in culpa qui officia deserunt mollit anim id est laborum.

"""

my_text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, \
           sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \
           Ut enim ad minim veniam, quis nostrud exercitation ullamco \
           laboris nisi ut aliquip ex ea commodo consequat. \
           Duis aute irure dolor in reprehenderit in voluptate velit \
           esse cillum dolore eu fugiat nulla pariatur. \
           Excepteur sint occaecat cupidatat non proident, \
           sunt in culpa qui officia deserunt mollit anim id est laborum."

print(len(my_text))

"""
Exercise 5: Longest word without a specific character
Instructions
Keep asking the user to input the longest sentence they can without the character “A”.
Each time a user successfully sets a new longest sentence, print a congratulations message.
"""

longest_sentence = ""

while True:
 sentence = input("Enter the longest sentence you can without the character 'A': ")
 if 'a' in sentence.lower():
    print("Your sentence contains the character 'a'. Try again.")
    continue

 if len(sentence) > len(longest_sentence):
    longest_sentence = sentence
    print("Congratulations! You've set a new longest sentence:", sentence)
 else:
    print("Your sentence is not longer than the current longest sentence.")